mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('recipe/', include('recipe.urls')),
    path('admin/', admin.site.urls),
]

recipe/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.add_recipe, name="create"),
    path('<int:recipe_id>', views.recipe_detail, name='detail'),
    url(r'^signup/$', views.signup, name='signup'),
]

recipe/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published', 
        default=timezone.now)
    views = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    amount = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

class Instruction(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    priority = models.IntegerField()
    description = models.CharField(max_length=200)
    
    class Meta:
        ordering = ['priority']
    
    def __str__(self):
        return self.description
    

recipe/forms.py
from django import forms
from .models import Recipe, Instruction, Ingredient #come back to this
from datetime import datetime

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'description', 'author', )

class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        fields = ('description', )

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ('name', 'amount', )

recipe/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .models import Recipe
from .forms import RecipeForm, InstructionForm, IngredientForm
from django.forms.formsets import formset_factory



def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'recipe/login.html', {'form': form})

# Create your views here.
def index(request):
    latest_recipe_list = Recipe.objects.order_by('-pub_date')[:5]
    context = {"recipe_list": latest_recipe_list}
    return render(request, "recipe/index.html", context)

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    recipe.views += 1
    recipe.save()
    return render(request, "recipe/recipe_detail.html", {"r": recipe})

def add_recipe(request):
    InstructionFormSet = formset_factory(InstructionForm, extra=3,
                                    min_num=1, validate_min=True)
    IngredientFormSet = formset_factory(IngredientForm, extra=3,
                                    min_num=1, validate_min=True)
    if request.method == 'POST':
        form = RecipeForm(request.POST)
        ingredients = IngredientFormSet(request.POST)
        instructions = InstructionFormSet(request.POST)
        if all([form.is_valid(), ingredients.is_valid(), instructions.is_valid()]):
            rec = form.save()

            # go through all the ingredients and save
            for ingredient in ingredients:
                if ingredient.cleaned_data:
                    i = ingredient.save(commit=False)
                    i.recipe = rec
                    i.save()
            # instructions
            for num, instruction in enumerate(instructions):
                if instruction.cleaned_data:
                    i = instruction.save(commit=False)
                    i.recipe = rec
                    i.priority = num
                    i.save()
            return render(request, "recipe/recipe_detail.html", {"r": rec})
    else:
        form = RecipeForm()
        instructionFormset = InstructionFormSet()
        ingredientFormset = IngredientFormSet()

    return render(request, 'recipe/add_recipe.html', 
        {'form': form, 'instructionformset': instructionFormset,
         'ingredientformset': ingredientFormset})

recipe/templates/recipe/add_recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Recipe</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <table>{{ form }}</table>
            <h1>Instructions:</h1>
            <table>{{ instructionformset }}</table>
            <h1>Ingredients:</h1>
            <table>{{ ingredientformset }}</table>
            <button>Submit</button>
        </form>
    </div>
 </body>
</html> 

recipe/templates/recipe/index.html
{% if recipe_list %}
    <ul>
    {% for r in recipe_list %}
        <li><a href="{% url 'detail' r.id %}">{{ r.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>uh oh spaghetti o</p>
{% endif %}

recipe/templates/recipe/login.html
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>

recipe/templates/recipe/recipe_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Recipe</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <h1>{{r.title}}</h1>
        <p>By: {{r.author}}</p>
        <h6>{{r.description}}</h6>
        <p>Views: {{r.views}}</p>
        <h3>Ingredients</h3>
        <ul class="list-group">
            {%for i in r.ingredient_set.all%}
                <li class="list-group-item">{{i.amount}} {{i.name}}</li>
            {% endfor %}
        </ul>
    
        <h3>Directions</h3>
        <ol>
            {%for i in r.instruction_set.all%}
                <li>{{i.description}}</li>
            {% endfor %}
        </ol>
    </div>
 </body>
</html> 